version: '3.8' # Add version to your YAML

services:
  # Nginx service
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # PHP service
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html/ 

  # MySQL service
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      # Chose host port 4306 because MySQL is already running on 3306
      - "4306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php

volumes:
  mysqldata:
